### ISSUE TITLE
Who is maintaining this project, and what is its status?

### ISSUE THREAD

**Issue by LappleApple** [zalando/axiom-web#15]
Please add a maintainers file with the names and email addresses, as per our guidelines. And is this project going forward? If not, let's move it to the [Incubator](https://github.com/zalando-incubator).

**Comment by avb1989** [comment]
Hi,
I'm the maintainer for this project now. The devs who started it have left the org. 
It is not under active development for now.

Will add the file, and maybe we should move it to the incubator. I'd wait for a couple of days to see what other contributors say.

**Comment by LappleApple** [comment]
@avb1989 Are their other contributors at this point? In any case, sounds like a good plan.

**Comment by LappleApple** [comment]
@avb1989 can we move to the Incubator now? :)

**Comment by avb1989** [comment]
I guess so :)

**Comment by LappleApple** [comment]
@avb1989 I just transferred to the Incubator and made you the maintainer of the project, lmk if you have any issues w/access. :)
